# Generated by Django 4.1.7 on 2023-04-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('stakeholders_if', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200)),
                ('priority', models.CharField(max_length=200)),
            ],
        ),
    ]
