# Generated by Django 4.1.7 on 2023-04-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_task_category_remove_task_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task',
        ),
        migrations.RemoveField(
            model_name='date',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category'),
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.date'),
        ),
        migrations.AddField(
            model_name='task',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Desc',
        ),
    ]
