# Generated by Django 4.1.7 on 2023-04-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_desc_task_task_date_task_desc_delete_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
